import { signal, effect } from "@preact/signals-core";
import * as anime from "animejs";
import { debounce, isNotNil } from "es-toolkit";
import AnyTouch from "any-touch";

// Optional controller returned by user-provided Boxjs snippets.
// Today Slipst only calls onWheel, mainly for static/manual animation mode.
type BoxjsController = {
  onWheel?: (context: {
    anime: typeof anime;
    root: ShadowRoot;
    host: HTMLElement;
    box: BoxjsInfo;
    event: WheelEvent;
    deltaY: number;
  }) => void;
};

type BoxjsInfo = {
  // Zero-based DOM order of the widget among all Boxjs widgets.
  index: number;
  // Unique id generated by Typst and applied to the outer host element.
  id: string;
  // Widget category: "boxjs" by default, "animejs" for the Anime.js template.
  kind: string;
};

// Keep runtime state for each inline Boxjs widget created from Typst metadata.
const boxjsBoxes = new Map<
  HTMLElement,
  { root: ShadowRoot; controller: BoxjsController; info: BoxjsInfo }
>();

// Three interaction modes, cycled with middle-click.
// - "slip": wheel scrolls slips/alters (default).
// - "animation": wheel is forwarded to active boxjs widgets.
// - "section": wheel scrolls between horizontal sections.
type Mode = "slip" | "animation" | "section";
const currentMode = signal<Mode>("slip");

// Instantiate every .slipst-boxjs placeholder emitted by slipst.typ.
// Each widget is isolated in a ShadowRoot so its local CSS does not leak into the slide.
function initBoxjsBoxes() {
  document.querySelectorAll(".slipst-boxjs").forEach((host, index) => {
    if (!(host instanceof HTMLElement) || boxjsBoxes.has(host)) return;

    const root = host.attachShadow({ mode: "open" });
    const html = host.getAttribute("data-slipst-boxjs-html") ?? "";
    const css = host.getAttribute("data-slipst-boxjs-css") ?? "";
    const js = host.getAttribute("data-slipst-boxjs-js") ?? "";
    const info = {
      index,
      id: host.getAttribute("data-slipst-boxjs-id") ?? host.id,
      kind: host.getAttribute("data-slipst-boxjs-kind") ?? "boxjs",
    };

    root.innerHTML = `
      <style>
        :host {
          display: block;
          width: 100%;
          height: 100%;
          box-sizing: border-box;
          contain: layout paint;
        }
        ${css}
      </style>
      ${html}
    `;

    let controller: BoxjsController = {};
    try {
      // User snippets are stored as source text in data attributes and evaluated here.
      // Parameters passed to the snippet:
      // - anime: bundled Anime.js module;
      // - root: ShadowRoot containing the user's html/css;
      // - host: outer .slipst-boxjs element;
      // - box: metadata object with index, id, and kind.
      const setup = new Function("anime", "root", "host", "box", js) as (
        anime: typeof anime,
        root: ShadowRoot,
        host: HTMLElement,
        box: BoxjsInfo,
      ) => BoxjsController | void;
      controller = setup(anime, root, host, info) ?? {};
    } catch (error) {
      console.error("Slipst boxjs widget failed to initialize", error);
    }

    boxjsBoxes.set(host, { root, controller, info });
  });
}

// Only widgets inside the currently active slip/alter should receive runtime events.
function activeBoxjsBoxes() {
  return Array.from(boxjsBoxes.entries()).filter(([host]) => {
    const slip = host.closest(".slip");
    if (!(slip instanceof HTMLElement)) return false;

    const sectionIndex = parseInt(slip.getAttribute("data-section") ?? "0", 10);
    const slipIndex = parseInt(slip.getAttribute("data-slip") ?? "0", 10);
    const alterIndex = parseInt(
      slip.getAttribute("data-slip-alter-idx") ?? "1",
      10,
    );

    // Previous slips can stay visible in Slipst, but they are not active.
    // Static-mode wheel events must only reach the current slip/alter.
    return (
      sectionIndex === currentSection.value &&
      slipIndex === currentSlip.value &&
      alterIndex === currentSlipAlter.value
    );
  });
}

// Forward a wheel event to active Boxjs widgets in static mode.
function sendWheelToBoxjsBoxes(event: WheelEvent) {
  const boxes = activeBoxjsBoxes();
  if (boxes.length === 0) return false;

  boxes.forEach(([host, box]) => {
    box.controller.onWheel?.({
      anime,
      root: box.root,
      host,
      box: box.info,
      event,
      deltaY: event.deltaY,
    });
  });
  return true;
}

// Send a synthetic deltaY to active Boxjs widgets (used by keyboard in animation mode).
function sendDeltaToBoxjsBoxes(deltaY: number) {
  const boxes = activeBoxjsBoxes();
  boxes.forEach(([host, box]) => {
    box.controller.onWheel?.({
      anime,
      root: box.root,
      host,
      box: box.info,
      event: new WheelEvent("wheel"),
      deltaY,
    });
  });
}

// Typst may export direct SVG frames; make those responsive inside a slip.
document.querySelectorAll(".slip > svg").forEach((svg) => {
  if (svg instanceof SVGElement) {
    svg.style.width = "100%";
    svg.style.height = "auto";
  }
});

/**
 * Parse the hash in the URL to get the current section, slip, and alter index.
 * The hash should be in the format "#section-slip-alter".
 */
function parseHash() {
  const hashGroups =
    /^(?<section>\d+)(?:-(?<slip>\d+))?(?:-(?<alter>\d+))?/.exec(
      location.hash.slice(1),
    )?.groups;

  let section = parseInt(hashGroups?.section ?? "1", 10);
  if (isNaN(section) || section < 1) {
    section = 1;
  }

  let slip = parseInt(hashGroups?.slip ?? "1", 10);
  if (isNaN(slip) || slip < 1) {
    slip = 1;
  }

  let alter = parseInt(hashGroups?.alter ?? "1", 10);
  if (isNaN(alter) || alter < 1) {
    alter = 1;
  }

  return { section, slip, alter };
}

const {
  section: initialSection,
  slip: initialSlip,
  alter: initialAlter,
} = parseHash();

// Presentation state. Signals re-run the layout/visibility effects below when changed.
const currentSection = signal(initialSection);
const currentSlip = signal(initialSlip);
const currentSlipAlter = signal(initialAlter);

// Persist navigation in the URL so refresh/share/back-to-position works.
effect(() => {
  const hash = `#${currentSection.value}-${currentSlip.value}-${currentSlipAlter.value}`;
  if (location.hash !== hash) {
    history.replaceState(null, "", hash);
  }
});

// Accept manual URL hash changes and synchronize them back into signals.
window.addEventListener("hashchange", () => {
  const { section, slip, alter } = parseHash();
  if (section !== currentSection.value) {
    currentSection.value = section;
  }
  if (slip !== currentSlip.value) {
    currentSlip.value = slip;
  }
  if (alter !== currentSlipAlter.value) {
    currentSlipAlter.value = alter;
  }
});

// Highest section index generated by the Typst side.
const maxSection = Array.from(document.querySelectorAll(".section"))
  .map((section) => {
    const attr = section.getAttribute("data-section");
    return attr !== null ? parseInt(attr, 10) : 0;
  })
  .reduce((a, b) => Math.max(a, b), 0);

/**
 * Map from section index to number of slips in that section.
 */
const sectionSlipCounts = new Map(
  Array.from(document.querySelectorAll(".section")).map((section) => {
    const attrSection = section.getAttribute("data-section");
    const attrCount = section.getAttribute("data-section-slip-count");
    const sectionIndex = attrSection !== null ? parseInt(attrSection, 10) : 0;
    const slipCount = attrCount !== null ? parseInt(attrCount, 10) : 1;
    return [sectionIndex, slipCount] as const;
  }),
);

/**
 * Map from a section/slip pair to number of alters.
 */
const slipAlters = new Map(
  Array.from(document.querySelectorAll(".slip")).map((slip) => {
    const attrSection = slip.getAttribute("data-section");
    const attrSlip = slip.getAttribute("data-slip");
    const attrAlter = slip.getAttribute("data-slip-alter-num");
    const sectionIndex = attrSection !== null ? parseInt(attrSection, 10) : 0;
    const slipIndex = attrSlip !== null ? parseInt(attrSlip, 10) : 0;
    const alterNum = attrAlter !== null ? parseInt(attrAlter, 10) : 1;
    return [`${sectionIndex}:${slipIndex}`, alterNum] as const;
  }),
);

function slipAlterKey(section: number, slip: number) {
  return `${section}:${slip}`;
}

/**
 * Go to the next slip or alter. Stops at the end of the current section.
 */
function nextSlip() {
  const alterNum =
    slipAlters.get(slipAlterKey(currentSection.value, currentSlip.value)) ?? 1;
  const slipCount = sectionSlipCounts.get(currentSection.value) ?? 1;
  if (currentSlipAlter.value < alterNum) {
    currentSlipAlter.value += 1;
  } else if (currentSlip.value < slipCount) {
    currentSlip.value += 1;
    currentSlipAlter.value = 1;
  }
}

/**
 * Go to the previous slip or alter. Stops at the beginning of the current section.
 */
function previousSlip() {
  if (currentSlipAlter.value > 1) {
    currentSlipAlter.value -= 1;
  } else if (currentSlip.value > 1) {
    currentSlip.value -= 1;
    const alterNum =
      slipAlters.get(slipAlterKey(currentSection.value, currentSlip.value)) ??
      1;
    currentSlipAlter.value = alterNum;
  }
}

/**
 * Go to the first slip of the next horizontal section.
 */
function nextSection() {
  if (currentSection.value < maxSection) {
    currentSection.value += 1;
    currentSlip.value = 1;
    currentSlipAlter.value = 1;
  }
}

/**
 * Go to the previous horizontal section. If toEnd is true, land on the last slip/alter.
 */
function previousSection(toEnd = false) {
  if (currentSection.value > 1) {
    currentSection.value -= 1;
    if (toEnd) {
      const lastSlip = sectionSlipCounts.get(currentSection.value) ?? 1;
      currentSlip.value = lastSlip;
      const lastAlter =
        slipAlters.get(slipAlterKey(currentSection.value, lastSlip)) ?? 1;
      currentSlipAlter.value = lastAlter;
    } else {
      currentSlip.value = 1;
      currentSlipAlter.value = 1;
    }
  }
}

const main = document.querySelector("main");

// Mouse wheels can emit many events; debounce keeps navigation to one step per gesture.
const navigateWheel = debounce(
  (event: WheelEvent) => {
    if (event.deltaY > 0) {
      // Wheel down: if at end of section, go to next section.
      if (isAtSectionEnd()) {
        nextSection();
      } else {
        nextSlip();
      }
    } else {
      // Wheel up: if at beginning of section, go to end of previous section.
      if (isAtSectionStart()) {
        previousSection(true);
      } else {
        previousSlip();
      }
    }
  },
  50,
  { edges: ["leading"] },
);

// Wheel reactivity: disable transitions during rapid scrolling, restore after a pause.
// Reads the configured duration from the CSS variable set by Typst.
const restoreTransitions = debounce(
  () => {
    document.documentElement.style.removeProperty("--transition-duration");
  },
  300,
  { edges: ["trailing"] },
);

// Check if the current position is the last slip/alter of the current section.
function isAtSectionEnd(): boolean {
  const slipCount = sectionSlipCounts.get(currentSection.value) ?? 1;
  const alterNum =
    slipAlters.get(slipAlterKey(currentSection.value, currentSlip.value)) ?? 1;
  return currentSlip.value >= slipCount && currentSlipAlter.value >= alterNum;
}

// Check if the current position is the first slip/alter of the current section.
function isAtSectionStart(): boolean {
  return currentSlip.value <= 1 && currentSlipAlter.value <= 1;
}

// Double-click/double-space detection: a fast second input at the end of a section jumps to the next section.
let clickTimer: ReturnType<typeof setTimeout> | null = null;

function handleClickOrSpace() {
  // Ensure transitions are active for click/space navigation.
  document.documentElement.style.removeProperty("--transition-duration");

  // If at end of section, wait briefly for a double input.
  if (isAtSectionEnd()) {
    if (clickTimer) {
      // Second input within 200ms → next section.
      clearTimeout(clickTimer);
      clickTimer = null;
      nextSection();
      return;
    }
    clickTimer = setTimeout(() => {
      // Single input at end of section → just nextSlip (stays in place).
      clickTimer = null;
    }, 200);
  } else {
    nextSlip();
  }
}

if (main) {
  // Left click: with transitions. Double-click at section end → next section.
  main.addEventListener("click", () => handleClickOrSpace());

  // Middle-click: short press cycles slip ↔ section, long press toggles animation mode.
  let middleDownTime = 0;
  main.addEventListener("mousedown", (event) => {
    if (event.button === 1) {
      event.preventDefault();
      middleDownTime = Date.now();
    }
  });
  main.addEventListener("auxclick", (event) => {
    if (event.button !== 1) return;
    event.preventDefault();

    // Any middle-click while in animation mode exits back to slip mode.
    if (currentMode.value === "animation") {
      currentMode.value = "slip";
      return;
    }

    const duration = Date.now() - middleDownTime;
    if (duration > 400) {
      currentMode.value = "animation";
    } else {
      currentMode.value = currentMode.value === "slip" ? "section" : "slip";
    }
  });

  // Wheel: no transitions, section wrapping. In animation mode, forwards to widgets.
  main.addEventListener(
    "wheel",
    (event) => {
      document.documentElement.style.setProperty("--transition-duration", "0s");
      restoreTransitions();

      if (currentMode.value === "animation") {
        sendWheelToBoxjsBoxes(event);
        event.preventDefault();
      } else if (currentMode.value === "section") {
        event.deltaY > 0 ? nextSection() : previousSection();
        event.preventDefault();
      } else {
        navigateWheel(event);
      }
    },
    { passive: false },
  );

  // Touch gestures.
  const anyTouch = new AnyTouch(main);
  anyTouch.on("swipeup", () => {
    document.documentElement.style.setProperty("--transition-duration", "0s");
    restoreTransitions();
    if (isAtSectionStart()) {
      previousSection(true);
    } else {
      previousSlip();
    }
  });
  anyTouch.on("swipeleft", nextSection);
  anyTouch.on("swiperight", () => previousSection());
  anyTouch.on("swipedown", () => {
    document.documentElement.style.setProperty("--transition-duration", "0s");
    restoreTransitions();
    if (isAtSectionEnd()) {
      nextSection();
    } else {
      nextSlip();
    }
  });
}

// Keyboard navigation for presenter remotes and common slideshow shortcuts.
document.addEventListener("keydown", (event) => {
  // In animation mode, arrow keys control boxjs widgets (simulate wheel).
  if (currentMode.value === "animation") {
    if (["ArrowRight", "ArrowDown"].includes(event.key)) {
      event.preventDefault();
      sendDeltaToBoxjsBoxes(100);
      return;
    } else if (["ArrowLeft", "ArrowUp"].includes(event.key)) {
      event.preventDefault();
      sendDeltaToBoxjsBoxes(-100);
      return;
    }
  }

  // Arrow Up/Down: no transitions, section wrapping (like wheel).
  if (event.key === "ArrowUp" || event.key === "PageUp") {
    event.preventDefault();
    document.documentElement.style.setProperty("--transition-duration", "0s");
    restoreTransitions();
    if (isAtSectionStart()) {
      previousSection(true);
    } else {
      previousSlip();
    }
  } else if (event.key === "ArrowDown" || event.key === "PageDown") {
    event.preventDefault();
    document.documentElement.style.setProperty("--transition-duration", "0s");
    restoreTransitions();
    if (isAtSectionEnd()) {
      nextSection();
    } else {
      nextSlip();
    }
  } else if (event.key === "ArrowRight") {
    event.preventDefault();
    nextSection();
  } else if (event.key === "ArrowLeft") {
    event.preventDefault();
    previousSection();
  }
});

// Enter key: toggles animation mode directly.
document.addEventListener("keyup", (event) => {
  if (event.key === "Enter") {
    event.preventDefault();

    // Enter always toggles animation mode (no cycle needed since arrows handle sections).
    if (currentMode.value === "animation") {
      currentMode.value = "slip";
    } else {
      currentMode.value = "animation";
    }
  }
});

// Space: with transitions. Double-space at section end → next section.
document.addEventListener("keydown", (event) => {
  if (event.key === " " && !event.ctrlKey && !event.metaKey) {
    event.preventDefault();
    handleClickOrSpace();
  }
});

initBoxjsBoxes();

// Collect all notes from the DOM, indexed by section:slip.
// Deduplicated: when a slip has #alter(n), the same slip is rendered n times
// with identical data-notes. We only keep one entry per section:slip pair.
interface NoteEntry {
  section: number;
  slip: number;
  text: string;
}
const allNotes: NoteEntry[] = [];
const seenNotes = new Set<string>();
document.querySelectorAll(".slip[data-notes]").forEach((el) => {
  const section = parseInt(el.getAttribute("data-section") ?? "0", 10);
  const slip = parseInt(el.getAttribute("data-slip") ?? "0", 10);
  const key = `${section}:${slip}`;
  if (seenNotes.has(key)) return;
  seenNotes.add(key);
  allNotes.push({
    section,
    slip,
    text: el.getAttribute("data-notes") ?? "",
  });
});

// BroadcastChannel for syncing with the notes window.
const notesChannel =
  typeof BroadcastChannel !== "undefined"
    ? new BroadcastChannel("slipst-notes")
    : null;

let notesWindow: Window | null = null;

function sendNotesToWindow() {
  if (!notesChannel) return;
  notesChannel.postMessage({
    type: "update",
    currentSection: currentSection.value,
    currentSlip: currentSlip.value,
    maxSection,
    notes: allNotes,
  });
}

function openNotesWindow() {
  if (notesWindow && !notesWindow.closed) {
    notesWindow.focus();
    sendNotesToWindow();
    return;
  }

  notesWindow = window.open("", "slipst-notes", "width=520,height=700");
  if (!notesWindow) return;

  const doc = notesWindow.document;
  doc.open();
  doc.write(
    "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Slipst \u2014 Speaker Notes</title>",
  );
  const style = doc.createElement("style");
  style.textContent = [
    "* { margin: 0; padding: 0; box-sizing: border-box; }",
    "body { font-family: system-ui, -apple-system, sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 1em; font-size: 14px; }",
    "h1 { font-size: 1.1em; color: #888; margin-bottom: 0.8em; border-bottom: 1px solid #333; padding-bottom: 0.4em; }",
    ".section-block { margin-bottom: 1.2em; }",
    ".section-title { font-size: 0.85em; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.4em; }",
    ".note { padding: 0.5em 0.7em; margin-bottom: 0.3em; border-radius: 0.4em; border-left: 3px solid transparent; opacity: 0.4; transition: opacity 0.3s, background 0.3s, border-color 0.3s; }",
    ".note.past { opacity: 0.3; border-left-color: #555; }",
    ".note.current { opacity: 1; background: #16213e; border-left-color: #e94560; color: #fff; }",
    ".note.future { opacity: 0.5; border-left-color: #0f3460; }",
    ".note .slip-label { font-size: 0.75em; color: #888; margin-bottom: 0.2em; }",
    ".note.current .slip-label { color: #e94560; }",
    ".no-notes { color: #555; font-style: italic; padding: 1em 0; }",
  ].join("\n");
  doc.head!.appendChild(style);
  doc.write("</head><body>");
  doc.write("<h1>Speaker Notes</h1><div id='notes-content'></div>");

  const renderScript = doc.createElement("script");
  renderScript.textContent = `
    const ch = new BroadcastChannel("slipst-notes");
    ch.onmessage = (event) => {
      if (event.data.type !== "update") return;
      render(event.data);
    };
    function render(data) {
      const container = document.getElementById("notes-content");
      if (!container) return;
      if (data.notes.length === 0) {
        container.innerHTML = '<div class="no-notes">No notes found. Use #notes[...] in your presentation.</div>';
        return;
      }
      const sections = new Map();
      for (const note of data.notes) {
        const key = note.section;
        if (!sections.has(key)) sections.set(key, []);
        sections.get(key).push(note);
      }
      let html = "";
      for (const [sectionIdx, sectionNotes] of sections) {
        html += '<div class="section-block">';
        html += '<div class="section-title">Section ' + sectionIdx + " / " + data.maxSection + "</div>";
        for (const note of sectionNotes) {
          let cls = "future";
          if (sectionIdx < data.currentSection) {
            cls = "past";
          } else if (sectionIdx === data.currentSection) {
            if (note.slip < data.currentSlip) {
              cls = "past";
            } else if (note.slip === data.currentSlip) {
              cls = "current";
            } else {
              cls = "future";
            }
          }
          html += '<div class="note ' + cls + '">';
          html += '<div class="slip-label">Slip ' + note.slip + "</div>";
          html += "<div>" + note.text + "</div>";
          html += "</div>";
        }
        html += "</div>";
      }
      container.innerHTML = html;
      // Auto-scroll to keep the current note visible.
      const current = container.querySelector(".note.current");
      if (current) {
        current.scrollIntoView({ behavior: "smooth", block: "nearest" });
      }
    }
  `;
  doc.body!.appendChild(renderScript);
  doc.write("</body></html>");
  doc.close();
  sendNotesToWindow();
}

// Sync notes window whenever navigation changes.
effect(() => {
  // Access reactive values to trigger re-run on change.
  const _s = currentSection.value;
  const _sl = currentSlip.value;
  sendNotesToWindow();
});

// N key opens the notes window.
document.addEventListener("keydown", (event) => {
  if (event.key === "n" || event.key === "N") {
    if (
      event.target instanceof HTMLInputElement ||
      event.target instanceof HTMLTextAreaElement
    )
      return;
    event.preventDefault();
    openNotesWindow();
  }
});

// Inject the section/mode overlay into <main>.
if (main) {
  const overlay = document.createElement("div");
  overlay.id = "slipst-overlay";
  overlay.innerHTML = `<span class="slipst-overlay-text"></span>`;
  main.appendChild(overlay);
}

// Update overlay text and color whenever navigation or mode changes.
effect(() => {
  const text = document.querySelector(".slipst-overlay-text");
  const overlay = document.getElementById("slipst-overlay");
  if (!text || !overlay) return;

  text.textContent = `${currentSection.value}.${currentSlip.value} / ${maxSection}`;

  const colors: Record<Mode, string> = {
    slip: "rgba(0, 0, 0, 0.45)",
    animation: "rgba(59, 130, 246, 0.65)",
    section: "rgba(234, 88, 12, 0.65)",
  };
  overlay.style.background = colors[currentMode.value];
});

// Toggle visibility of every generated slip layer.
// Previous slips keep only their final alter visible; current slip shows its active alter;
// future slips stay hidden until navigation reaches them.
effect(() => {
  document.querySelectorAll(".slip").forEach((slip) => {
    const attrSlip = slip.getAttribute("data-slip");
    const slipIndex = attrSlip !== null ? parseInt(attrSlip, 10) : 0;

    const attrSection = slip.getAttribute("data-section");
    const sectionIndex = attrSection !== null ? parseInt(attrSection, 10) : 0;

    const attrAlter = slip.getAttribute("data-slip-alter-idx");
    const alterIdx = attrAlter !== null ? parseInt(attrAlter, 10) : 1;

    if (slip instanceof HTMLElement) {
      if (sectionIndex !== currentSection.value) {
        // Inactive sections are prepared at their first slip so horizontal
        // navigation arrives at the beginning instead of moving diagonally.
        if (slipIndex === 1 && alterIdx === 1) {
          slip.style.opacity = "1";
        } else {
          slip.style.opacity = "0";
        }
      } else if (slipIndex < currentSlip.value) {
        // Previous slips, only show the last alter.
        if (
          alterIdx !==
          (slipAlters.get(slipAlterKey(sectionIndex, slipIndex)) ?? 1)
        ) {
          slip.style.opacity = "0";
        } else {
          slip.style.opacity = "1";
        }
      } else if (slipIndex === currentSlip.value) {
        // Current slip, show the current alter.
        if (alterIdx === currentSlipAlter.value) {
          slip.style.opacity = "1";
        } else {
          slip.style.opacity = "0";
        }
      } else {
        // Future slips, hide all alters.
        slip.style.opacity = "0";
      }
    }
  });
});

// Move the vertical container according to the latest active #up action.
// Without #up, the deck stays aligned to the top; with #up, the target slip is brought up.
const layoutEffect = () => {
  const sectionContainer = document.getElementById("section-container");
  const section = document.querySelector(
    `.section[data-section="${currentSection.value}"]`,
  );
  if (
    sectionContainer instanceof HTMLElement &&
    section instanceof HTMLElement
  ) {
    sectionContainer.style.left = `${-section.offsetLeft}px`;
  }

  document.querySelectorAll(".slip-container").forEach((container) => {
    if (container instanceof HTMLElement) {
      container.style.top = "0";
    }
  });

  // Find the nearest slip with a "data-slip-up" attribute, starting from the current slip and going upwards.
  let up = document
    .querySelector(
      `.slip[data-section="${currentSection.value}"][data-slip="${currentSlip.value}"]`,
    )
    ?.getAttribute("data-slip-up");
  let dy = document
    .querySelector(
      `.slip[data-section="${currentSection.value}"][data-slip="${currentSlip.value}"]`,
    )
    ?.getAttribute("data-slip-dy");
  let end = document
    .querySelector(
      `.slip[data-section="${currentSection.value}"][data-slip="${currentSlip.value}"]`,
    )
    ?.getAttribute("data-slip-end");

  for (let i = currentSlip.value - 1; i > 0; i--) {
    if (isNotNil(up)) break;
    up = document
      .querySelector(
        `.slip[data-section="${currentSection.value}"][data-slip="${i}"]`,
      )
      ?.getAttribute("data-slip-up");
    dy = document
      .querySelector(
        `.slip[data-section="${currentSection.value}"][data-slip="${i}"]`,
      )
      ?.getAttribute("data-slip-dy");
    end = document
      .querySelector(
        `.slip[data-section="${currentSection.value}"][data-slip="${i}"]`,
      )
      ?.getAttribute("data-slip-end");
  }
  const endDyRaw = getComputedStyle(
    document.getElementById("section-container")!,
  )
    .getPropertyValue("--end-dy")
    .trim()
    .replace(/\u2212/g, "-");
  const endDyValue = endDyRaw ? parseFloat(endDyRaw) : 0;
  const startDyRaw = getComputedStyle(
    document.getElementById("section-container")!,
  )
    .getPropertyValue("--start-dy")
    .trim()
    .replace(/\u2212/g, "-");
  const startDyValue = startDyRaw ? parseFloat(startDyRaw) : 0;
  let dyValue = isNotNil(dy) ? parseFloat(dy.replace(/\u2212/g, "-")) : 0;
  if (isNotNil(up)) {
    const anchors = document.querySelectorAll(`[data-global-slip="${up}"]`);
    const anchor = Array.from(anchors)
      .filter((anchor) => anchor instanceof HTMLElement)
      .filter(
        (anchor) => window.getComputedStyle(anchor).display !== "none",
      )[0];
    const container = document.querySelector(
      `.slip-container[data-section="${currentSection.value}"]`,
    );
    if (!(anchor instanceof HTMLElement)) {
      console.warn(`Slipst #up target does not exist: global slip ${up}`);
    }
    if (anchor instanceof HTMLElement && container instanceof HTMLElement) {
      const marginTop =
        parseFloat(window.getComputedStyle(container).marginTop) || 0;
      if (end === "true") {
        // Align the target slip bottom with the viewport bottom.
        const viewportHeight =
          container.closest("main")?.clientHeight ?? window.innerHeight;
        const anchorBottom =
          marginTop + anchor.offsetTop + anchor.getBoundingClientRect().height;
        const totalDy = dyValue + endDyValue;
        const sign = totalDy >= 0 ? "+" : "-";
        container.style.top = `calc(${viewportHeight - anchorBottom}px ${sign} ${Math.abs(totalDy)} * var(--slip-1cm))`;
      } else {
        const totalDy = dyValue + startDyValue;
        if (totalDy !== 0) {
          const sign = totalDy >= 0 ? "-" : "+";
          container.style.top = `calc(${-anchor.offsetTop - marginTop}px ${sign} ${Math.abs(totalDy)} * var(--slip-1cm))`;
        } else {
          container.style.top = `${-anchor.offsetTop - marginTop}px`;
        }
      }
    }
  }
};
effect(layoutEffect);

// During resize, recompute layout instantly to avoid seeing an animated correction jump.
if (document.defaultView) {
  document.defaultView.addEventListener("resize", () => {
    document.documentElement.style.setProperty("--transition-duration", "0s");
    document.documentElement.style.setProperty(
      "--section-transition-duration",
      "0s",
    );
    layoutEffect();
    setTimeout(() => {
      document.documentElement.style.removeProperty("--transition-duration");
      document.documentElement.style.removeProperty(
        "--section-transition-duration",
      );
    }, 1);
  });
}
